<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SyncSourceEmployeesSeeder extends Seeder
{
    /**
     * Seed HRIS/HRMS source employees from CSV data.
     * Hard-coded data synchronized from seeders.csv.
     */
    public function run(): void
    {
        $rows = [
            // HRIS - Row 1: Direktur Utama
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1001',
                'name' => 'Direktur Utama',
                'date_joined' => '2018-01-02',
                'email' => 'direktur@wiscore.id',
                'whatsapp' => '81234501001',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'General',
                'department' => 'General',
                'position' => 'Direktur Utama',
                'placement' => 'Surabaya',
                'level' => 'Direktur',
                'manager_functional' => '-',
                'manager_operational' => '-',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 2: PCX Manager
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1002',
                'name' => 'PCX Manager',
                'date_joined' => '2021-07-12',
                'email' => 'pcx@wiscore.id',
                'whatsapp' => '81234501002',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'People, Culture and Experiences',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Manager User',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 3: Intercomm User
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1003',
                'name' => 'Intercomm User',
                'date_joined' => '2021-07-12',
                'email' => 'intercomm@wiscore.id',
                'whatsapp' => '81234501003',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'People, Culture and Experiences',
                'position' => 'Internal Communication Specialist',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'manager_functional' => 'Manager User',
                'manager_operational' => 'PCX Manager',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 4: Manager User
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1004',
                'name' => 'Manager User',
                'date_joined' => '2020-02-17',
                'email' => 'manager@wiscore.id',
                'whatsapp' => '81234501004',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'General',
                'position' => 'General Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Direktur Utama',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 5: Employee User
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1005',
                'name' => 'Employee User',
                'date_joined' => '2024-01-10',
                'email' => 'employee@wiscore.id',
                'whatsapp' => '81234501005',
                'company' => 'PT Gawih Djaja',
                'division' => 'Information Technology',
                'department' => 'Webapp Dev',
                'position' => 'Web Junior Developer',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Fajar Nugroho',
                'manager_operational' => 'Developer',
                'employee_status' => 'PKWT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 6: Developer
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1006',
                'name' => 'Developer',
                'date_joined' => '2022-09-05',
                'email' => 'dev@wiscore.id',
                'whatsapp' => '81234501006',
                'company' => 'PT Gawih Djaja',
                'division' => 'Information Technology',
                'department' => 'Webapp Dev',
                'position' => 'Webapp Developer Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Fajar Nugroho',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 7: Fajar Nugroho
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2001',
                'name' => 'Fajar Nugroho',
                'date_joined' => '2020-03-09',
                'email' => 'fajar@wiscore.id',
                'whatsapp' => '81234501007',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Information Technology',
                'department' => 'General',
                'position' => 'General Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Direktur Utama',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 8: Rina Marlina
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2002',
                'name' => 'Rina Marlina',
                'date_joined' => '2021-08-03',
                'email' => 'rina@wiscore.id',
                'whatsapp' => '81234501008',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'People, Culture and Experiences',
                'position' => 'HR Bussiness Partner Staf',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Manager User',
                'manager_operational' => 'PCX Manager',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 9: Agung Prasetyo
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2003',
                'name' => 'Agung Prasetyo',
                'date_joined' => '2021-09-14',
                'email' => 'agung@wiscore.id',
                'whatsapp' => '81234501009',
                'company' => 'PT Gawih Djaja',
                'division' => 'Human Resource',
                'department' => 'C&B and HRIS',
                'position' => 'C&B and HRIS Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Manager User',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 10: Tasya Handayani
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2004',
                'name' => 'Tasya Handayani',
                'date_joined' => '2021-10-11',
                'email' => 'tasya@wiscore.id',
                'whatsapp' => '81234501010',
                'company' => 'PT Gawih Djaja',
                'division' => 'Human Resource',
                'department' => 'C&B and HRIS',
                'position' => 'Employee Assurance Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'manager_functional' => 'Manager User',
                'manager_operational' => 'Agung Prasetyo',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 11: Rizal Maulana
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2005',
                'name' => 'Rizal Maulana',
                'date_joined' => '2022-01-05',
                'email' => 'rizal@wiscore.id',
                'whatsapp' => '81234501011',
                'company' => 'PT Gawih Djaja',
                'division' => 'Human Resource',
                'department' => 'C&B and HRIS',
                'position' => 'HRIS Maintenance Staff',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Manager User',
                'manager_operational' => 'Agung Prasetyo',
                'employee_status' => 'PKWT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 12: Nanda Saputra
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2006',
                'name' => 'Nanda Saputra',
                'date_joined' => '2022-02-07',
                'email' => 'nanda@wiscore.id',
                'whatsapp' => '81234501012',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'Recruitment',
                'position' => 'Recruitment Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Manager User',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 13: Putri Maharani
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2007',
                'name' => 'Putri Maharani',
                'date_joined' => '2022-03-14',
                'email' => 'putri@wiscore.id',
                'whatsapp' => '81234501013',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'Recruitment',
                'position' => 'Regional Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'manager_functional' => 'Manager User',
                'manager_operational' => 'Nanda Saputra',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 14: Bima Adityawan
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2008',
                'name' => 'Bima Adityawan',
                'date_joined' => '2022-04-11',
                'email' => 'bima@wiscore.id',
                'whatsapp' => '81234501014',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'Recruitment',
                'position' => 'Recruitment Staff',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Manager User',
                'manager_operational' => 'Nanda Saputra',
                'employee_status' => 'PKWT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 15: Maya Dwi Lestari
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2009',
                'name' => 'Maya Dwi Lestari',
                'date_joined' => '2022-01-18',
                'email' => 'maya@wiscore.id',
                'whatsapp' => '81234501015',
                'company' => 'PT Gelora Djaja',
                'division' => 'Information Technology',
                'department' => 'Technical Support',
                'position' => 'TS Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Fajar Nugroho',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 16: Yusuf Hidayat
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2010',
                'name' => 'Yusuf Hidayat',
                'date_joined' => '2022-02-21',
                'email' => 'yusuf@wiscore.id',
                'whatsapp' => '81234501016',
                'company' => 'PT Gelora Djaja',
                'division' => 'Information Technology',
                'department' => 'Technical Support',
                'position' => 'Technical Support',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'manager_functional' => 'Fajar Nugroho',
                'manager_operational' => 'Maya Dwi Lestari',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 17: Intan Maharani
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2011',
                'name' => 'Intan Maharani',
                'date_joined' => '2022-03-15',
                'email' => 'intan@wiscore.id',
                'whatsapp' => '81234501017',
                'company' => 'PT Gawih Djaja',
                'division' => 'Information Technology',
                'department' => 'IT - SAP',
                'position' => 'SAP Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Fajar Nugroho',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 18: Deni Kurniawan
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2012',
                'name' => 'Deni Kurniawan',
                'date_joined' => '2022-05-11',
                'email' => 'deni@wiscore.id',
                'whatsapp' => '81234501018',
                'company' => 'PT Gawih Djaja',
                'division' => 'Information Technology',
                'department' => 'IT - SAP',
                'position' => 'SAP Production',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Fajar Nugroho',
                'manager_operational' => 'Intan Maharani',
                'employee_status' => 'PKWT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 19: Ardiansyah Putra
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2013',
                'name' => 'Ardiansyah Putra',
                'date_joined' => '2022-06-20',
                'email' => 'ardiansyah@wiscore.id',
                'whatsapp' => '81234501019',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'General',
                'position' => 'HRGA Specialist',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Manager User',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 20: Nabila Rahmawati
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2015',
                'name' => 'Nabila Rahmawati',
                'date_joined' => '2021-06-14',
                'email' => 'nabila@wiscore.id',
                'whatsapp' => '81234501021',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'General',
                'position' => 'Sekretaris HR',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Manager User',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 21: Ahnaf Fathan
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2016',
                'name' => 'Ahnaf Fathan',
                'date_joined' => '2023-07-08',
                'email' => 'ahnaf@wiscore.id',
                'whatsapp' => '81234234509',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Information Technology',
                'department' => 'General',
                'position' => 'Network and Hardware Mainteance',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Fajar Nugroho',
                'employee_status' => 'PKWTT',
                'status' => 'Aktif',
            ],
            // HRIS - Row 22: Regina Dwi
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2017',
                'name' => 'Regina Dwi',
                'date_joined' => '2022-10-30',
                'email' => 'regina@wiscore.id',
                'whatsapp' => '89759976188',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Information Technology',
                'department' => 'General',
                'position' => 'IT Quality Audit',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'manager_functional' => 'Direktur Utama',
                'manager_operational' => 'Fajar Nugroho',
                'employee_status' => 'PKWT',
                'status' => 'Aktif',
            ],
            // HRMS - Row 23: Rifaldi Fathur
            [
                'source_system' => 'HRMS',
                'employee_number' => 'OUT1001',
                'name' => 'Rifaldi Fathur',
                'date_joined' => '2023-04-03',
                'email' => 'rifaldi@wiscore.id',
                'whatsapp' => '89765384728',
                'company' => 'PT Outsourcing Globalindo',
                'division' => 'FAT',
                'department' => 'Factory Production',
                'position' => 'Production Staff',
                'placement' => 'Surabaya',
                'level' => 'Mingguan',
                'manager_functional' => '-',
                'manager_operational' => '-',
                'employee_status' => 'OS',
                'status' => 'Aktif',
            ],
            // HRMS - Row 24: Jessie Agustina
            [
                'source_system' => 'HRMS',
                'employee_number' => 'OUT1002',
                'name' => 'Jessie Agustina',
                'date_joined' => '2022-11-15',
                'email' => 'jessie@wiscore.id',
                'whatsapp' => '87579075290',
                'company' => 'PT Outsourcing Globalindo',
                'division' => 'FAT',
                'department' => 'Accounting Purchase',
                'position' => 'Cashflow Management Assisten',
                'placement' => 'Surabaya',
                'level' => 'Harian',
                'manager_functional' => '-',
                'manager_operational' => '-',
                'employee_status' => 'OS',
                'status' => 'Aktif',
            ],
            // HRMS - Row 25: Mardi Susanto
            [
                'source_system' => 'HRMS',
                'employee_number' => 'OUT1003',
                'name' => 'Mardi Susanto',
                'date_joined' => '2023-01-10',
                'email' => 'mardi@wiscore.id',
                'whatsapp' => '81234601001',
                'company' => 'PT Outsourcing Globalindo',
                'division' => 'FAT',
                'department' => 'Tax Record',
                'position' => 'Tax Management Staff',
                'placement' => 'Surabaya',
                'level' => 'Borongan',
                'manager_functional' => '-',
                'manager_operational' => '-',
                'employee_status' => 'OS',
                'status' => 'Aktif',
            ],
        ];

        $now = now();

        foreach ($rows as $row) {
            DB::table('sync_source_employees')->updateOrInsert(
                [
                    'source_system' => $row['source_system'],
                    'employee_number' => $row['employee_number'],
                ],
                [
                    ...$row,
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );
        }
    }
}
