<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SyncSourceEmployeesSeeder extends Seeder
{
    /**
     * Seed dummy readable source data from HRIS and HRMS systems.
     */
    public function run(): void
    {
        $rows = [
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP0001',
                'name' => 'Dina Prameswari',
                'date_joined' => '2022-01-17',
                'email' => 'dina.prameswari@wismilak.co.id',
                'whatsapp' => '081234500001',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Capital',
                'department' => 'C&B and HRIS',
                'position' => 'Staf/Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP0002',
                'name' => 'Rifki Mahendra',
                'date_joined' => '2021-08-03',
                'email' => 'rifki.mahendra@wismilak.co.id',
                'whatsapp' => '081234500002',
                'company' => 'PT Gelora Djaja',
                'division' => 'Sales',
                'department' => 'Area East',
                'position' => 'Staf/Supervisor',
                'placement' => 'Malang',
                'level' => 'Supervisor',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP0003',
                'name' => 'Silfia Nur Aini',
                'date_joined' => '2024-03-12',
                'email' => 'silfia.nuraini@wismilak.co.id',
                'whatsapp' => '081234500003',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Technology',
                'department' => 'Product Engineering',
                'position' => 'Mingguan',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP0004',
                'name' => 'Nadya Paramitha',
                'date_joined' => '2021-11-01',
                'email' => 'nadya.paramitha@wismilak.co.id',
                'whatsapp' => '081234500004',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP0005',
                'name' => 'Aditiya Ramadhan',
                'date_joined' => '2020-09-14',
                'email' => 'aditiya.ramadhan@wismilak.co.id',
                'whatsapp' => '081234500005',
                'company' => 'PT Gelora Djaja',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Manager',
                'placement' => 'Jakarta',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP0006',
                'name' => 'Rangga Prakoso',
                'date_joined' => '2022-05-09',
                'email' => 'rangga.prakoso@wismilak.co.id',
                'whatsapp' => '081234500006',
                'company' => 'PT Gawih Djaja',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1001',
                'name' => 'Direktur Utama',
                'date_joined' => '2018-01-02',
                'email' => 'direktur@vnb.id',
                'whatsapp' => '081234501001',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Strategic Leadership',
                'department' => 'Board of Directors',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Director',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1002',
                'name' => 'PCX Manager',
                'date_joined' => '2020-02-17',
                'email' => 'pcx@vnb.id',
                'whatsapp' => '081234501002',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1003',
                'name' => 'Intercomm User',
                'date_joined' => '2021-07-12',
                'email' => 'intercomm@vnb.id',
                'whatsapp' => '081234501003',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Staf/Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1004',
                'name' => 'Manager User',
                'date_joined' => '2019-04-08',
                'email' => 'manager@vnb.id',
                'whatsapp' => '081234501004',
                'company' => 'PT Gawih Djaja',
                'division' => 'Finance & Business Support',
                'department' => 'Financial Planning & Analysis (FP&A)',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1005',
                'name' => 'Employee User',
                'date_joined' => '2024-01-10',
                'email' => 'employee@vnb.id',
                'whatsapp' => '081234501005',
                'company' => 'PT Gelora Djaja',
                'division' => 'Operations (Pusat Produksi)',
                'department' => 'Primary Process (Pemrosesan bahan baku/daun)',
                'position' => 'Harian',
                'placement' => 'Bandung',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1006',
                'name' => 'Developer',
                'date_joined' => '2022-09-05',
                'email' => 'dev@vnb.id',
                'whatsapp' => '081234501006',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Technology',
                'department' => 'Product Engineering',
                'position' => 'Borongan',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRMS',
                'employee_number' => 'OUTSRC001',
                'name' => 'Ahmad Fauzi Pratama',
                'date_joined' => '2023-06-15',
                'email' => 'ahmad.fauzi@outsourcing.co.id',
                'whatsapp' => '081234500101',
                'company' => 'PT Outsourcing Partners',
                'division' => 'Operations',
                'department' => 'Warehouse',
                'position' => 'Warehouse Staff',
                'placement' => 'Gresik',
                'level' => 'Staff',
                'employee_status' => 'OS',
            ],
            [
                'source_system' => 'HRMS',
                'employee_number' => 'OUTSRC002',
                'name' => 'Siti Nurhasanah',
                'date_joined' => '2024-01-10',
                'email' => 'siti.nurhasanah@outsourcing.co.id',
                'whatsapp' => '081234500102',
                'company' => 'PT Outsourcing Partners',
                'division' => 'Production',
                'department' => 'Line Production',
                'position' => 'Production Operator',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'OS',
            ],
        ];

        $now = now();

        foreach ($rows as $row) {
            DB::table('sync_source_employees')->updateOrInsert(
                [
                    'source_system' => $row['source_system'],
                    'employee_number' => $row['employee_number'],
                ],
                [
                    ...$row,
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );
        }
    }
}
