<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SyncSourceEmployeesSeeder extends Seeder
{
    /**
     * Seed dummy readable source data from HRIS and HRMS systems.
     */
    public function run(): void
    {
        $rows = [
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1001',
                'name' => 'Direktur Utama',
                'date_joined' => '2018-01-02',
                'email' => 'direktur@vnb.id',
                'whatsapp' => '081234501001',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'General',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Director',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1002',
                'name' => 'PCX Manager',
                'date_joined' => '2021-07-12',
                'email' => 'pcx@vnb.id',
                'whatsapp' => '081234501002',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1003',
                'name' => 'Intercomm User',
                'date_joined' => '2021-07-12',
                'email' => 'intercomm@vnb.id',
                'whatsapp' => '081234501003',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Staf/Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1004',
                'name' => 'Manager User',
                'date_joined' => '2020-02-17',
                'email' => 'manager@vnb.id',
                'whatsapp' => '081234501004',
                'company' => 'PT Gawih Djaja',
                'division' => 'Human Resource',
                'department' => 'General',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'General Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1005',
                'name' => 'Employee User',
                'date_joined' => '2024-01-10',
                'email' => 'employee@vnb.id',
                'whatsapp' => '081234501005',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Webapp Dev',
                'position' => 'Harian',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP1006',
                'name' => 'Developer',
                'date_joined' => '2022-09-05',
                'email' => 'dev@vnb.id',
                'whatsapp' => '081234501006',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Webapp Dev',
                'position' => 'Borongan',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2001',
                'name' => 'Fajar Nugroho',
                'date_joined' => '2020-03-09',
                'email' => 'it.gm@vnb.id',
                'whatsapp' => '081234501007',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'General',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'General Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2002',
                'name' => 'Rina Marlina',
                'date_joined' => '2021-08-03',
                'email' => 'cnb-hris.manager@vnb.id',
                'whatsapp' => '081234501008',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'C&B and HRIS',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2003',
                'name' => 'Agung Prasetyo',
                'date_joined' => '2021-09-14',
                'email' => 'pod.manager@vnb.id',
                'whatsapp' => '081234501009',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People Operations and Development',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2004',
                'name' => 'Tasya Handayani',
                'date_joined' => '2021-10-11',
                'email' => 'recruitment.manager@vnb.id',
                'whatsapp' => '081234501010',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'Recruitment',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2005',
                'name' => 'Rizal Maulana',
                'date_joined' => '2022-01-05',
                'email' => 'techsupport.manager@vnb.id',
                'whatsapp' => '081234501011',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Technical Support',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2006',
                'name' => 'Nanda Saputra',
                'date_joined' => '2022-02-07',
                'email' => 'webapp.manager@vnb.id',
                'whatsapp' => '081234501012',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Webapp Dev',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2007',
                'name' => 'Putri Maharani',
                'date_joined' => '2022-03-14',
                'email' => 'sap.manager@vnb.id',
                'whatsapp' => '081234501013',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'SAP',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2008',
                'name' => 'Bima Adityawan',
                'date_joined' => '2022-04-11',
                'email' => 'infra.manager@vnb.id',
                'whatsapp' => '081234501014',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Infrastructure & Security',
                'position' => 'Manager',
                'placement' => 'Surabaya',
                'level' => 'Manager',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2009',
                'name' => 'Maya Dwi Lestari',
                'date_joined' => '2022-01-18',
                'email' => 'cnb.staff@vnb.id',
                'whatsapp' => '081234501015',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'C&B and HRIS',
                'position' => 'Staf/Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2010',
                'name' => 'Yusuf Hidayat',
                'date_joined' => '2022-02-21',
                'email' => 'pod.staff@vnb.id',
                'whatsapp' => '081234501016',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People Operations and Development',
                'position' => 'Mingguan',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2011',
                'name' => 'Intan Maharani',
                'date_joined' => '2022-03-15',
                'email' => 'recruitment.staff@vnb.id',
                'whatsapp' => '081234501017',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'Recruitment',
                'position' => 'Harian',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2012',
                'name' => 'Deni Kurniawan',
                'date_joined' => '2022-05-11',
                'email' => 'techsupport.staff@vnb.id',
                'whatsapp' => '081234501018',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Technical Support',
                'position' => 'Staf/Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2013',
                'name' => 'Ardiansyah Putra',
                'date_joined' => '2022-06-20',
                'email' => 'sap.staff@vnb.id',
                'whatsapp' => '081234501019',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'SAP',
                'position' => 'Borongan',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'employee_status' => 'PKWTT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2014',
                'name' => 'Lukman Hakim',
                'date_joined' => '2022-07-04',
                'email' => 'infra.staff@vnb.id',
                'whatsapp' => '081234501020',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'IT',
                'department' => 'Infrastructure & Security',
                'position' => 'Mingguan',
                'placement' => 'Surabaya',
                'level' => 'Staff',
                'employee_status' => 'PKWT',
            ],
            [
                'source_system' => 'HRIS',
                'employee_number' => 'EMP2015',
                'name' => 'Nabila Rahmawati',
                'date_joined' => '2021-06-14',
                'email' => 'pcx.specialist@vnb.id',
                'whatsapp' => '081234501021',
                'company' => 'PT Wismilak Inti Makmur',
                'division' => 'Human Resource',
                'department' => 'People, Culture, and Experiences',
                'position' => 'Staf/Supervisor',
                'placement' => 'Surabaya',
                'level' => 'Supervisor',
                'employee_status' => 'PKWTT',
            ],
        ];

        $now = now();

        foreach ($rows as $row) {
            DB::table('sync_source_employees')->updateOrInsert(
                [
                    'source_system' => $row['source_system'],
                    'employee_number' => $row['employee_number'],
                ],
                [
                    ...$row,
                    'updated_at' => $now,
                    'created_at' => $now,
                ]
            );
        }
    }
}
