<?php

namespace Database\Seeders;

use App\Models\VnbFrameworkItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VnbFrameworkSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing data (disable foreign keys first)
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        VnbFrameworkItem::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $items = [
            // manage_self_non_staff (1-42)
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Empathy', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Empathy', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Empathy', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Speak with Data', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Speak with Data', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Speak with Data', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Collaborative', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Collaborative', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Collaborative', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Decisive', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Decisive', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Decisive', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Open Mind', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Open Mind', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Open Mind', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Empathy', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Empathy', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Empathy', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Speak with Data', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Speak with Data', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Speak with Data', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Collaborative', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Collaborative', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Collaborative', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Decisive', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Decisive', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Decisive', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Open Mind', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Open Mind', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Open Mind', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            // manage_function & manage_others & manage_managers dengan integration data dari SQL
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Empathy', 'phase' => '1-3', 'integration_1' => 'Memberikan apresiasi tertulis kepada rekan-rekan kerjanya', 'integration_2' => 'Bertanya kepada rekan satu tim tentang tantangan atau kesulitan yang mereka hadapi, memberikan saran atau membantu mereka sesuai dengan wewenang dan tanggung jawab'],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Empathy', 'phase' => '4-6', 'integration_1' => 'Inisiatif Menawarkan bantuan pada rekan kerja yang membutuhkan bantuan sesuai dengan ranahnya', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Empathy', 'phase' => '6+', 'integration_1' => 'Membantu mengenalkan cara kerja ke rekan baru', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1-3', 'integration_1' => 'Mempelajari sejarah atau filosofi perusahaan, lalu membagikan 1 hal yang paling menginspirasi', 'integration_2' => 'Mengunggah atau membagikan konten positif tentang kegiatan perusahaan di media sosial internal/perusahaan (jika diperbolehkan)'],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '4-6', 'integration_1' => 'Mengikuti aktivitas-aktivitas Wismilak', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '6+', 'integration_1' => 'Menjadi contoh kedisiplinan', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '1-3', 'integration_1' => 'Mengetahui ranah pekerjaannya sesuai job desc dan visi misi perusahaan', 'integration_2' => 'Mengikuti pelatihan penggunaan alat kerja/SOP yang benar dan membuat laporan singkat pemahaman'],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '4-6', 'integration_1' => 'Disiplin Bekerja sesuai dengan target perusahaan (waktu dan materi)', 'integration_2' => 'Mengusulkan ide-ide (>1) untuk menyederhanakan pekerjaan harian atau sistem kerja & standarisasi'],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '6+', 'integration_1' => 'Menghindari melakukan kesalahan berulang. Dan dapat Mengingatkan rekan jika kerja tidak sesuai SOP', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Speak with Data', 'phase' => '1-3', 'integration_1' => 'Melaporkan hasil kerja sesuai jumlah nyata', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Speak with Data', 'phase' => '4-6', 'integration_1' => 'Mengakui kesalahan tanpa ditutup-tutupi', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Speak with Data', 'phase' => '6+', 'integration_1' => 'Menyampaikan jika hasil turun & cari penyebab', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Collaborative', 'phase' => '1-3', 'integration_1' => 'Mengetahui peran tim yang terlibat dalam pekerja hariannya', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Collaborative', 'phase' => '4-6', 'integration_1' => 'Saling membantu / back up rekan kerja ketika dibutuhkan untuk mencapai target perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Collaborative', 'phase' => '6+', 'integration_1' => 'Menjaga suasana kerja kondusif (Hal apa saja yang dapat dilakukan untuk mencapai hal ini)', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Decisive', 'phase' => '1-3', 'integration_1' => 'Langsung melapor jika ada kendala---Mengajukan solusi untuk penyelesaian masalah dalam pekerjaan harian, kemudian konsultasikan kepada atasan sebelum dilakukan', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Decisive', 'phase' => '4-6', 'integration_1' => 'Tidak membiarkan kesalahan berulang --- Menyampaikan kepada atasan peluang atau masalah (loophole) yang dapat berdampak ke departemen, divisi, atau perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Decisive', 'phase' => '6+', 'integration_1' => 'Memberi saran sederhana jika lihat potensi masalah', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Open Mind', 'phase' => '1-3', 'integration_1' => 'Meminta dan memberikan 1 feedback dari atasan, rekan kerja, atau team dan menerapkannya.', 'integration_2' => 'Menyampaikan hambatan yang dialami kepada Atasan dan menyusun Action Plan untuk mengatasinya'],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Open Mind', 'phase' => '4-6', 'integration_1' => 'Mengetahui kelebihan dan kekurangan yang dimiliki selama bekerja, dan dipersilahkan mengajukan pelatihan apabila diperlukan', 'integration_2' => null],
            ['career_stage' => 'manage_self_non_staff', 'behaviour' => 'Open Mind', 'phase' => '6+', 'integration_1' => 'Berani menyampaikan ide unik/kreatif (tanpa takut salah) kepada atasan', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Empathy', 'phase' => '1-3', 'integration_1' => 'Memberikan apresiasi tertulis kepada rekan-rekan kerjanya', 'integration_2' => 'Bertanya kepada rekan satu tim tentang tantangan atau kesulitan yang mereka hadapi, memberikan saran atau membantu mereka sesuai dengan wewenang dan tanggung jawab'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Empathy', 'phase' => '4-6', 'integration_1' => 'Menginisiasi diskusi dengan rekan berbeda divisi / departemen (klien internal) atau klien eksternal untuk memahami tantangan dan membantu mereka sesuai dengan wewenang dan tanggung jawab', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Empathy', 'phase' => '6+', 'integration_1' => 'Karyawan ditugaskan menjadi "buddy" untuk rekan baru atau rekan satu tim dalam project tertentu', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1-3', 'integration_1' => 'Mempelajari sejarah atau filosofi perusahaan, lalu membagikan 1 hal yang paling menginspirasi', 'integration_2' => 'Mengunggah atau membagikan konten positif tentang kegiatan perusahaan di media sosial internal/perusahaan (jika diperbolehkan)'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '4-6', 'integration_1' => 'Mengikuti aktivitas-aktivitas Wismilak', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '6+', 'integration_1' => 'Menjadi panitia, pelaksana, atau koordinator dalam minimal 1 event perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '1-3', 'integration_1' => 'Mengisi template "Visi & Misi Alignment Map": mencocokkan pekerjaan harian dengan kontribusinya terhadap visi & misi perusahaan', 'integration_2' => 'Mengikuti pelatihan penggunaan alat kerja / SOP yang benar dan membuat laporan ringkas pemahaman'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '4-6', 'integration_1' => 'Membuat pertimbangan cost vs benefit perusahaan dari pekerjaan yang dilakukan', 'integration_2' => 'Mengusulkan ide-ide (>1) untuk menyederhanakan pekerjaan harian atau sistem kerja & standarisasi'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Effective & Efficient', 'phase' => '6+', 'integration_1' => 'Melatih 1 rekan kerja tentang tips kerja efisien yang sudah ter-standard', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Speak with Data', 'phase' => '1-3', 'integration_1' => 'Belajar membaca atau memahami minimal 1 jenis data dasar yang digunakan di divisinya (misalnya: output, volume, target)', 'integration_2' => 'Mencatat minimal 1 hal yang bisa diukur dari pekerjaannya dan melacak progresnya'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Speak with Data', 'phase' => '4-6', 'integration_1' => 'Menyusun target kerja (Specific, Measurable, Achievable, Reachable, Time bound) berdasarkan data yang dikumpulkan', 'integration_2' => 'Menyusun dan presentasi laporan berbasis data dari pekerjaan yang dilakukan'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Speak with Data', 'phase' => '6+', 'integration_1' => 'Memberikan usulan pada proses kerja berdasarkan data yang dipresentasikan dan menunjukkan progress.', 'integration_2' => 'Studi kasus: membedakan mana data atau informasi milik Divisi dan Perusahaan yang boleh dan tidak boleh disebarluaskan'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Collaborative', 'phase' => '1-3', 'integration_1' => 'Identifikasi impact pekerjaan karyawan pada bagian, departemen atau divisi lain (user) untuk mengenal peran mereka dan sebaliknya', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Collaborative', 'phase' => '4-6', 'integration_1' => 'Ikut serta dalam 1 kegiatan atau project tim lintas fungsi', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Collaborative', 'phase' => '6+', 'integration_1' => 'Mengusulkan dan menjadi koordinator kolaborasi baru yang bisa menguntungkan dua tim/departemen/divisi', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Decisive', 'phase' => '1-3', 'integration_1' => 'Mengajukan solusi untuk penyelesaian masalah dalam pekerjaan harian, kemudian konsultasikan kepada atasan sebelum dilakukan', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Decisive', 'phase' => '4-6', 'integration_1' => 'Menyampaikan kepada atasan peluang atau masalah (loophole) yang dapat berdampak ke departemen, divisi, atau perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Decisive', 'phase' => '6+', 'integration_1' => 'Memberi usulan strategis kepada atasan yang berdampak pada sistem/proses ke depan dan lanjutkan dengan PDCA (Plan , Do, Check, Action)', 'integration_2' => null],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Open Mind', 'phase' => '1-3', 'integration_1' => 'Meminta dan memberikan 1 feedback dari atasan, rekan kerja, atau team dan menerapkannya.', 'integration_2' => 'Menyampaikan hambatan yang dialami kepada Atasan dan menyusun Action Plan untuk mengatasinya'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Open Mind', 'phase' => '4-6', 'integration_1' => 'Membuat list Strength, Area for Development, dan mengikuti pelatihan yang sesuai', 'integration_2' => 'Menjadi fasilitator atau moderator dalam sesi diskusi untuk integrasi berbagai ide'],
            ['career_stage' => 'manage_self_staff', 'behaviour' => 'Open Mind', 'phase' => '6+', 'integration_1' => 'Menyampaikan ide unik/kreatif (tanpa takut salah) kepada atasan, lalu menilai bersama potensi pengembangannya.', 'integration_2' => null],
            // manage_others (148-189)
            ['career_stage' => 'manage_others', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1-3', 'integration_1' => 'Mempelajari sejarah atau filosofi perusahaan, lalu membagikan 1 hal yang paling menginspirasi', 'integration_2' => 'Mengunggah atau membagikan konten positif tentang kegiatan perusahaan di media sosial internal/perusahaan (jika diperbolehkan)'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '4-6', 'integration_1' => 'Mengikuti aktivitas-aktivitas Wismilak', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '6+', 'integration_1' => 'Menjadi panitia, pelaksana, atau koordinator dalam minimal 1 event perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Collaborative', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Collaborative', 'phase' => '1-3', 'integration_1' => 'Identifikasi impact pekerjaan karyawan pada bagian, departemen atau divisi lain (user) untuk mengenal peran mereka dan sebaliknya', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Collaborative', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Collaborative', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Collaborative', 'phase' => '4-6', 'integration_1' => 'Ikut serta dalam 1 kegiatan atau project tim lintas fungsi', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Collaborative', 'phase' => '6+', 'integration_1' => 'Mengusulkan dan menjadi koordinator kolaborasi baru yang bisa menguntungkan dua tim/departemen/divisi', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Decisive', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Decisive', 'phase' => '1-3', 'integration_1' => 'Mengajukan solusi untuk penyelesaian masalah dalam pekerjaan harian, kemudian konsultasikan kepada atasan sebelum dilakukan', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Decisive', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Decisive', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Decisive', 'phase' => '4-6', 'integration_1' => 'Menyampaikan kepada atasan peluang atau masalah (loophole) yang dapat berdampak ke departemen, divisi, atau perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Decisive', 'phase' => '6+', 'integration_1' => 'Memberi usulan strategis kepada atasan yang berdampak pada sistem/proses ke depan dan lanjutkan dengan PDCA (Plan , Do, Check, Action)', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Effective & Efficient', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Effective & Efficient', 'phase' => '1-3', 'integration_1' => 'Mengisi template "Visi & Misi Alignment Map": mencocokkan pekerjaan harian dengan kontribusinya terhadap visi & misi perusahaan', 'integration_2' => 'Mengikuti pelatihan penggunaan alat kerja / SOP yang benar dan membuat laporan ringkas pemahaman'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Effective & Efficient', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Effective & Efficient', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Effective & Efficient', 'phase' => '4-6', 'integration_1' => 'Membuat pertimbangan cost vs benefit perusahaan dari pekerjaan yang dilakukan', 'integration_2' => 'Mengusulkan ide-ide (>1) untuk menyederhanakan pekerjaan harian atau sistem kerja & standarisasi'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Effective & Efficient', 'phase' => '6+', 'integration_1' => 'Melatih 1 rekan kerja tentang tips kerja efisien yang sudah ter-standard', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Empathy', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Empathy', 'phase' => '1-3', 'integration_1' => 'Memberikan apresiasi tertulis kepada rekan-rekan kerjanya', 'integration_2' => 'Bertanya kepada rekan satu tim tentang tantangan atau kesulitan yang mereka hadapi, memberikan saran atau membantu mereka sesuai dengan wewenang dan tanggung jawab'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Empathy', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Empathy', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Empathy', 'phase' => '4-6', 'integration_1' => 'Menginisiasi diskusi dengan rekan berbeda divisi / departemen (klien internal) atau klien eksternal untuk memahami tantangan dan membantu mereka sesuai dengan wewenang dan tanggung jawab', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Empathy', 'phase' => '6+', 'integration_1' => 'Karyawan ditugaskan menjadi "buddy" untuk rekan baru atau rekan satu tim dalam project tertentu', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Open Mind', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Open Mind', 'phase' => '1-3', 'integration_1' => 'Meminta dan memberikan 1 feedback dari atasan, rekan kerja, atau team dan menerapkannya.', 'integration_2' => 'Menyampaikan hambatan yang dialami kepada Atasan dan menyusun Action Plan untuk mengatasinya'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Open Mind', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Open Mind', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Open Mind', 'phase' => '4-6', 'integration_1' => 'Membuat list Strength, Area for Development, dan mengikuti pelatihan yang sesuai', 'integration_2' => 'Menjadi fasilitator atau moderator dalam sesi diskusi untuk integrasi berbagai ide'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Open Mind', 'phase' => '6+', 'integration_1' => 'Menyampaikan ide unik/kreatif (tanpa takut salah) kepada atasan, lalu menilai bersama potensi pengembangannya.', 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Speak with Data', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Speak with Data', 'phase' => '1-3', 'integration_1' => 'Belajar membaca atau memahami minimal 1 jenis data dasar yang digunakan di divisinya (misalnya: output, volume, target)', 'integration_2' => 'Mencatat minimal 1 hal yang bisa diukur dari pekerjaannya dan melacak progresnya'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Speak with Data', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Speak with Data', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_others', 'behaviour' => 'Speak with Data', 'phase' => '4-6', 'integration_1' => 'Menyusun target kerja (Specific, Measurable, Achievable, Reachable, Time bound) berdasarkan data yang dikumpulkan', 'integration_2' => 'Menyusun dan presentasi laporan berbasis data dari pekerjaan yang dilakukan'],
            ['career_stage' => 'manage_others', 'behaviour' => 'Speak with Data', 'phase' => '6+', 'integration_1' => 'Memberikan usulan pada proses kerja berdasarkan data yang dipresentasikan dan menunjukkan progress.', 'integration_2' => 'Studi kasus: membedakan mana data atau informasi milik Divisi dan Perusahaan yang boleh dan tidak boleh disebarluaskan'],
            // manage_managers (190-231)
            ['career_stage' => 'manage_managers', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '1-3', 'integration_1' => 'Mempelajari sejarah atau filosofi perusahaan, lalu membagikan 1 hal yang paling menginspirasi', 'integration_2' => 'Mengunggah atau membagikan konten positif tentang kegiatan perusahaan di media sosial internal/perusahaan (jika diperbolehkan)'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '4-6', 'integration_1' => 'Mengikuti aktivitas-aktivitas Wismilak', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Be A Wismilak Ambassador', 'phase' => '6+', 'integration_1' => 'Menjadi panitia, pelaksana, atau koordinator dalam minimal 1 event perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Collaborative', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Collaborative', 'phase' => '1-3', 'integration_1' => 'Identifikasi impact pekerjaan karyawan pada bagian, departemen atau divisi lain (user) untuk mengenal peran mereka dan sebaliknya', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Collaborative', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Collaborative', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Collaborative', 'phase' => '4-6', 'integration_1' => 'Ikut serta dalam 1 kegiatan atau project tim lintas fungsi', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Collaborative', 'phase' => '6+', 'integration_1' => 'Mengusulkan dan menjadi koordinator kolaborasi baru yang bisa menguntungkan dua tim/departemen/divisi', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Decisive', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Decisive', 'phase' => '1-3', 'integration_1' => 'Mengajukan solusi untuk penyelesaian masalah dalam pekerjaan harian, kemudian konsultasikan kepada atasan sebelum dilakukan', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Decisive', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Decisive', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Decisive', 'phase' => '4-6', 'integration_1' => 'Menyampaikan kepada atasan peluang atau masalah (loophole) yang dapat berdampak ke departemen, divisi, atau perusahaan', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Decisive', 'phase' => '6+', 'integration_1' => 'Memberi usulan strategis kepada atasan yang berdampak pada sistem/proses ke depan dan lanjutkan dengan PDCA (Plan , Do, Check, Action)', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Effective & Efficient', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Effective & Efficient', 'phase' => '1-3', 'integration_1' => 'Mengisi template "Visi & Misi Alignment Map": mencocokkan pekerjaan harian dengan kontribusinya terhadap visi & misi perusahaan', 'integration_2' => 'Mengikuti pelatihan penggunaan alat kerja / SOP yang benar dan membuat laporan ringkas pemahaman'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Effective & Efficient', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Effective & Efficient', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Effective & Efficient', 'phase' => '4-6', 'integration_1' => 'Membuat pertimbangan cost vs benefit perusahaan dari pekerjaan yang dilakukan', 'integration_2' => 'Mengusulkan ide-ide (>1) untuk menyederhanakan pekerjaan harian atau sistem kerja & standarisasi'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Effective & Efficient', 'phase' => '6+', 'integration_1' => 'Melatih 1 rekan kerja tentang tips kerja efisien yang sudah ter-standard', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Empathy', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Empathy', 'phase' => '1-3', 'integration_1' => 'Memberikan apresiasi tertulis kepada rekan-rekan kerjanya', 'integration_2' => 'Bertanya kepada rekan satu tim tentang tantangan atau kesulitan yang mereka hadapi, memberikan saran atau membantu mereka sesuai dengan wewenang dan tanggung jawab'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Empathy', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Empathy', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Empathy', 'phase' => '4-6', 'integration_1' => 'Menginisiasi diskusi dengan rekan berbeda divisi / departemen (klien internal) atau klien eksternal untuk memahami tantangan dan membantu mereka sesuai dengan wewenang dan tanggung jawab', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Empathy', 'phase' => '6+', 'integration_1' => 'Karyawan ditugaskan menjadi "buddy" untuk rekan baru atau rekan satu tim dalam project tertentu', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Open Mind', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Open Mind', 'phase' => '1-3', 'integration_1' => 'Meminta dan memberikan 1 feedback dari atasan, rekan kerja, atau team dan menerapkannya.', 'integration_2' => 'Menyampaikan hambatan yang dialami kepada Atasan dan menyusun Action Plan untuk mengatasinya'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Open Mind', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Open Mind', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Open Mind', 'phase' => '4-6', 'integration_1' => 'Membuat list Strength, Area for Development, dan mengikuti pelatihan yang sesuai', 'integration_2' => 'Menjadi fasilitator atau moderator dalam sesi diskusi untuk integrasi berbagai ide'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Open Mind', 'phase' => '6+', 'integration_1' => 'Menyampaikan ide unik/kreatif (tanpa takut salah) kepada atasan, lalu menilai bersama potensi pengembangannya.', 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Speak with Data', 'phase' => '1', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Speak with Data', 'phase' => '1-3', 'integration_1' => 'Belajar membaca atau memahami minimal 1 jenis data dasar yang digunakan di divisinya (misalnya: output, volume, target)', 'integration_2' => 'Mencatat minimal 1 hal yang bisa diukur dari pekerjaannya dan melacak progresnya'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Speak with Data', 'phase' => '2', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Speak with Data', 'phase' => '3', 'integration_1' => null, 'integration_2' => null],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Speak with Data', 'phase' => '4-6', 'integration_1' => 'Menyusun target kerja (Specific, Measurable, Achievable, Reachable, Time bound) berdasarkan data yang dikumpulkan', 'integration_2' => 'Menyusun dan presentasi laporan berbasis data dari pekerjaan yang dilakukan'],
            ['career_stage' => 'manage_managers', 'behaviour' => 'Speak with Data', 'phase' => '6+', 'integration_1' => 'Memberikan usulan pada proses kerja berdasarkan data yang dipresentasikan dan menunjukkan progress.', 'integration_2' => 'Studi kasus: membedakan mana data atau informasi milik Divisi dan Perusahaan yang boleh dan tidak boleh disebarluaskan'],
        ];

        foreach ($items as $item) {
            VnbFrameworkItem::create($item);
        }

        echo "V&B Framework seeder completed: " . count($items) . " items created (manage_self_non_staff, manage_self_staff, manage_others, manage_managers)\n";
    }
}
